version: "3.9"

services:
  backend:
    build: ./back-end
    container_name: nike_backend
    volumes:
      - ./back-end:/app
    ports:
      - "8001:8000"
    env_file:
      - ./back-end/.env
    depends_on:
      - db

  frontend:
    build: ./front-end
    container_name: nike_frontend
    volumes:
      - ./front-end:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: nike_db
    environment:
      POSTGRES_DB: nike
      POSTGRES_USER: nike
      POSTGRES_PASSWORD: nike
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
